### ISSUE TITLE
Use of get_doctype_counts

### ISSUE THREAD

**Issue by anchitjain1234** [codebox/bayesian-classifier#3]
I am not able to understand why you have created method `get_doctype_counts` in **db.py**.
You have called this function in **classifier.py** but have not used it there also.

Also while training in **learn.py** do we need to provided all the data in **single file**? 
If yes ,wont it be good if you ask **directory** as argument where all the input files are kept of the specified label?

**Comment by codebox** [comment]
db.py contains all code that accesses the database, hiding details of the database structure from the rest of the application. Since get_doctype_counts must run a query, it is contained inside db.py.

Each call to 'learn' must refer to a single file only, although you can make multiple calls each with a different file if you wish.

**Comment by anchitjain1234** [comment]
You could make a separate argument  in learn to specify whether to read from file or directory and read as specified.

**Comment by anchitjain1234** [comment]
In **words.py** could we also add **stemming** from _nltk_ ?
